export const SHORTLISTED_SOFTWARE = [
  { team: 'Syntax Error', leader: 'Aayush Rasaily', college: 'CMR Institute of Technology' },
  { team: 'BigForge', leader: 'Jashwanth N', college: 'CMR Institute of Technology' },
  { team: 'ArthSaathi', leader: 'Gagan Y', college: 'CMR Institute of Technology' },
  { team: 'Tech Ragnarök', leader: 'Prajwal G', college: 'CMRIT College of Engineering' },
  { team: 'Codeflakes', leader: 'Geeta Saunshi', college: 'Siddaganga Institute of Technology, Tumkur' },
  { team: 'Predators', leader: 'James C Pathadan', college: 'CMRIT' },
  { team: 'Zenith', leader: 'Aditya Kumar Jha', college: 'LNCT University' },
  { team: 'byte_X', leader: 'Aaditya Gupta', college: 'CMR Institute of Technology' },
  { team: 'Night Owls', leader: 'Manasvi Sutar', college: 'MVJ College of Engineering' },
  { team: 'Vortexa', leader: 'Ananya P', college: 'Mysuru Royal Institute of Technology' },
  { team: 'HEXAHERS', leader: 'Sanjana Kumari', college: 'CMRIT' },
  { team: 'AI Burst ⚡', leader: 'Uma Mahesh L', college: 'GM University' },
  { team: 'Quattrocrackers', leader: 'Shifanaaz', college: 'AMC Engineering College' },
  { team: 'EMBEDCRAFT', leader: 'Aaryan Upadhyay', college: 'CMRIT' },
  { team: 'Compile Craft', leader: 'Abhishek Kumar Choudhary', college: 'RVITM' },
  { team: 'Hackstreet Boys', leader: 'Tejas Y', college: 'Sapthagiri NPS University' },
  { team: 'Error 404', leader: 'Dalavai Vaishnavi', college: 'CMR Institute of Technology' },
  { team: 'CityZen', leader: 'DS Lokesh Gowda', college: 'CMRIT' },
  { team: 'HustleHer', leader: 'Prapti Srivastava', college: 'CMR Institute of Technology' },
  { team: 'Craetelox', leader: 'Rohit Gupta', college: 'Baderia Global Institute of Engineering and Management, Jabalpur' },
  { team: 'InnovateX', leader: 'Sonali S', college: 'CMR Institute of Technology' },
  { team: 'Tech Titans', leader: 'Jawaharram S', college: 'Sri Krishna College of Technology' },
  { team: 'TECH TITANS', leader: 'Pruthviraj Kale', college: 'Pimpri Chinchwad College of Engineering' },
  { team: 'Rapid Rebels', leader: 'Riddhika Sharma', college: 'Vijaya Vittala Institute of Technology' },
  { team: 'Tech Titans', leader: 'Tejashwini M', college: 'Ballari Institute of Technology and Management' },
  { team: 'Thinkers', leader: 'Sree Kanikadevi K', college: 'Chennai Institute of Technology' },
  { team: 'Tech Blaze', leader: 'Nishanth S', college: 'East West Institute of Technology' },
  { team: '4-Bits', leader: 'Aryan Shrinivas Sutar', college: 'Rajarambapu Institute of Technology, Rajaramnagar' },
  { team: 'City Sense', leader: 'Harshit Ranjan', college: 'National Institute of Technology Karnataka' },
  { team: 'CodeTitans', leader: 'Rishikesh', college: 'Nagarjuna College of Engineering & Technology' },
  { team: 'Cloud9', leader: 'Karthik S', college: 'Padre Conceicao College of Engineering' },
  { team: 'Ace', leader: 'Piyush Anil Thakre', college: 'Prof. Ram Meghe Institute of Technology and Research, Badnera' },
  { team: 'Marcos', leader: 'Manish Sharma', college: 'GMRIT Deemed to be University' },
  { team: 'EyeNova', leader: 'Bhavana N', college: 'Siddaganga Institute of Technology' },
  { team: 'AI QUADRANT', leader: 'Prathyaksh S', college: 'Vidyavardhaka College of Engineering Mysore' },
  { team: 'Black Dragon', leader: 'Dinesh R', college: 'SNS College of Engineering' },
  { team: 'STATUS 200', leader: 'M.V.S. Karthikeya', college: 'Kurnool, Andhra Pradesh' },
  { team: 'EcoSortAI+', leader: 'Ganga Vanaparthi', college: 'Mangaluru, Karnataka' },
  { team: 'TEAM BYTEFORCE', leader: 'Shreeraksha H S', college: 'Dayananda Sagar College of Engineering' },
  { team: 'Synergy', leader: 'Keshav Kunal', college: 'Ramaiah Institute of Technology' },
  { team: 'Code Revenants', leader: 'Santoshi Shrinivas Reddy', college: 'PDA College of Engineering' },
  { team: 'XLR-8', leader: 'Veerla Jishnu Teja', college: 'Cambridge Institute of Technology, Ramaiah University of Applied Sciences' },
  { team: 'Tech Initiators', leader: 'Arpitha Jain C B', college: 'Shree Dharmasthala Manjunatheshwara Institute of Technology (SDMIT), Ujire, Karnataka' },
  { team: 'FourLoop', leader: 'Moulya Mallikarjun', college: 'R V Institute of Technology and Management' },
  { team: 'Innovation Team', leader: 'S M Veeresh', college: 'Ballari Institute of Technology and Management' },
  { team: 'Code Storm 313', leader: 'Nisha Parween', college: 'Gandhi Engineering College' },
  { team: 'MUDRA-ML', leader: 'Premsagar Deshmane', college: 'SNJB\'s Late Sau. Kantabai Bhawarlalji Jain College of Engineering' },
  { team: 'Fiscal Force', leader: 'Bandhavi S S', college: 'Vidyavardhaka College of Engineering' },
  { team: 'CODE CRACKERS', leader: 'Infant Jenilia J', college: 'Sathyabama Institute of Science and Technology' },
  { team: 'Null Parking', leader: 'Eknath', college: 'Rajalakshmi Institute of Technology' },
  { team: 'Research Engines', leader: 'G P Dhanya', college: 'Bapuji Institute of Engineering and Technology' },
  { team: 'Wind Breakers', leader: 'Dhivakar S', college: 'K.S. Rangasamy College of Technology' },
  { team: 'Tiffin Wala RankBrain', leader: 'Bharat Pandey', college: 'Maharana Institute of Professional Studies' },
  { team: 'Nightingale', leader: 'Sahana M', college: 'Madras Institute of Technology, Anna University' },
  { team: 'AgroConnect360+', leader: 'Narmatha R', college: 'Chennai Institute of Technology' },
  { team: 'Avanthikamanoj900', leader: 'Avanthika Manoj', college: 'Amrita Vishwa Vidyapeetham' },
  { team: 'CropWise', leader: 'Padmanabhacharya', college: 'Kalaburgi, Karnataka, India' },
  { team: 'UrbanIQ', leader: 'Sonali Devkar', college: 'Solapur, Maharashtra' },
]

export const SHORTLISTED_HARDWARE = [
  { team: 'Route Rangers', leader: 'Varsha Kokatnur', college: 'CMR Institute of Technology' },
  { team: 'Novocaine', leader: 'Amritha M R', college: 'CMR Institute of Technology' },
  { team: 'Cobra Tech', leader: 'Akash B R', college: 'BNM Institute of Technology' },
  { team: 'THOR', leader: 'Sivasankara Mathesh M', college: 'K V Sala Higher Secondary School' },
  { team: 'Solcane', leader: 'G. Gautham Vas', college: 'CMRIT' },
  { team: 'BIO-VOLT', leader: 'Hardhik Bhatia', college: 'Sir M. Visvesvaraya Institute of Technology (SMVIT), Bengaluru' },
  { team: 'VERDE - Vehicle for Environmental Recon, Detection & Exploration', leader: 'Likitha N', college: 'CMR Institute of Technology' },
  { team: 'Vishwakarma', leader: 'Vedant Prakash Chilbule', college: 'SNS College of Technology' },
  { team: 'MedHide', leader: 'Geethanjali V N', college: 'MVJ College of Engineering' },
  { team: 'FIRE', leader: 'Sivakumar Balaji', college: 'PSNA College of Engineering and Technology' },
  { team: 'VARS', leader: 'Mohamed Aqeeb', college: 'CMR Institute of Technology' },
  { team: 'NotYetDecided', leader: 'Kuldeep Chouhan R', college: 'Siddaganga Institute of Technology' },
  { team: 'RootRhythm', leader: 'Sathvik A S', college: 'CMR Institute of Technology' },
  { team: 'Gestro Motion', leader: 'Abhigyan Paramanik', college: 'PM Shri KV Khurda Road' },
  { team: 'R.O.V.E.R — Recon & Observation Vehicle for Emergency Response', leader: 'Likitha N', college: 'CMRIT' },
  { team: 'TEAM VELOCITY-X', leader: 'Sneka Venkateswari M', college: 'Rajalakshmi Institute of Technology' },
  { team: 'DGTHON', leader: 'M. Raghul', college: 'None' },
  { team: 'Tech Hawks', leader: 'Nithin S', college: 'None' },
  { team: 'Ignited Minds', leader: 'Kalaiyarasu R', college: 'Vidyavardhaka College of Engineering' },
  { team: 'Toggle', leader: 'Dhanalakshmi D', college: 'Anna University (AU), Chennai' },
  { team: 'TEAM COGNYX', leader: 'Anu Priya D', college: 'None' },
  { team: 'MediSync AR', leader: 'None', college: 'Maharaja Institute of Technology Tandavpura' },
  { team: 'ECO MINDS', leader: 'Akshat Raj', college: 'Bannari Amman Institute of Technology' },
  { team: 'INVICTUS', leader: 'Jeevesh Sankar M', college: 'CMR Institute of Technology' },
  { team: 'Mavericks', leader: 'Richie Joen A', college: 'None' },
  { team: 'Technovative', leader: 'Piyush Kumar Singh', college: 'Cambridge Institute of Technology' },
]
